apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: s3-service
  name: s3-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: s3-service
  template:
    metadata:
      labels:
        app: s3-service
    spec:
      containers:
      - image: aaronlewis/s3-bucket-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        name: s3-service
        ports:
        - containerPort: 8300
          name: s3-service
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 8300
            path: /actuator/health/readiness
          initialDelaySeconds: 90
          periodSeconds: 90
        livenessProbe:
          httpGet:
            port: 8300
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 90
      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: s3-service
  name: s3-service
  namespace: default
spec:
  ports:
  - port: 8300
    protocol: TCP
    targetPort: 8300
  selector:
    app: s3-service
  sessionAffinity: None
  type: NodePort 
