apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: puzzle-service
  name: puzzle-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: puzzle-service
  template:
    metadata:
      labels:
        app: puzzle-service
    spec:
      containers:
      - image: aaronlewis/eight-puzzle-solver:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        name: experience-service
        ports:
        - containerPort: 8500
          name: puzzle-service
          protocol: TCP
        readinessProbe:
          httpGet:
            port: 8500
            path: /actuator/health/readiness
          initialDelaySeconds: 90
          periodSeconds: 90
        livenessProbe:
          httpGet:
            port: 8500
            path: /actuator/health/liveness
          initialDelaySeconds: 90
          periodSeconds: 90
      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: puzzle-service
  name: puzzle-service
  namespace: default
spec:
  ports:
  - port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    app: puzzle-service
  sessionAffinity: None
  type: NodePort
