server:
  port: 443

spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"

#management:
#  endpoint:
#    features:
#      enabled: 'true'
#    health:
#      probes:
#        enabled: 'true'
#  health:
#    livenessstate:
#      enabled: 'true'
#    readinessstate:
#      enabled: 'true'
